# Generated by Django 4.0.2 on 2022-03-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phonenumber',
        ),
    ]
