# Generated by Django 4.0.2 on 2022-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=25)),
                ('hazard', models.CharField(max_length=11)),
                ('discribe', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Media/')),
            ],
        ),
    ]
